/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { InsurancePolicy } from "./InsurancePolicy";
export * as factories from "./factories";
export { InsurancePolicy__factory } from "./factories/InsurancePolicy__factory";
